### ISSUE TITLE
Photo Upload

### ISSUE THREAD

**Issue by chf2** [lisamcho/final-project#3]
We'll do a demo of Cloudinary, an image uploading tool, in the next 2-3 days. Unless you're feeling very confident on integrating paperclip with Backbone, I'd try and hold off until you at least see what Cloudinary can offer for single-page responsiveness and uploads. 

File upload is one of those things that can occasionally go very awry and soak up a lot of time. Since you're doing it relatively early in the project, I'd recommend putting a hard cap on time spent at 1 day and moving on to more features after that before coming back to complete it if it's taking longer than expected to get fully functional.

**Comment by lisamcho** [comment]
Thanks! Good to know

**Comment by lisamcho** [comment]
Changed implementation of photos to TBD. I will wait until the Cloudinary demo to implement.
